#define SEIMEI_STATUS_HOST "192.168.1.23"
#define SEIMEI_STATUS_PORT 38019
#define SEIMEI_PROXY_HOST "192.168.1.52"
#define SEIMEI_DEFAULT_TIMEOUT 3

#define HSKYMON_SEIMEI_ERROR_GETHOST  -1
#define HSKYMON_SEIMEI_ERROR_SOCKET   -2
#define HSKYMON_SEIMEI_ERROR_CONNECT  -3
#define HSKYMON_SEIMEI_ERROR_FDGET    -4
#define HSKYMON_SEIMEI_ERROR_TEMPFILE -5
#define HSKYMON_SEIMEI_ERROR_SSL -6
