#define SEIMEI_STATUS_HOST "192.168.1.23"
#define SEIMEI_STATUS_PORT "38019"

#define HSKYMON_SEIMEI_ERROR_GETHOST  -1
#define HSKYMON_SEIMEI_ERROR_SOCKET   -2
#define HSKYMON_SEIMEI_ERROR_CONNECT  -3
#define HSKYMON_SEIMEI_ERROR_TEMPFILE -4
#define HSKYMON_SEIMEI_ERROR_SSL -5
